import { DataLoadError, type DataProvider, type ReadModelManifest, type RecordDetail, type RecordSummary } from "./types";
import { SUPPORTED_READ_MODEL_MAJOR, isReadModelVersionCompatible } from "./readModelCompatibility";

const BUILD_DATA_COMMAND = "node apps/research-explorer/scripts/build-data.js (or run `npm run explorer`)";

/**
 * Record IDs are generated by the RE-01 adapter (schema prefix + opaque
 * suffix, e.g. "PRB-0005", "EVD-000105") and are never expected to contain
 * path separators. This is a generic, prefix-agnostic shape check — it does
 * not hardcode SRC-/EVD-/PRB-/ASM-/HYP- — so a future schema-conforming
 * record type's ID remains resolvable without a provider change.
 */
const SAFE_ID_PATTERN = /^[A-Za-z][A-Za-z0-9]*-[A-Za-z0-9]+$/;

function isSyntacticallySafeId(id: string): boolean {
  return (
    typeof id === "string" &&
    id.length > 0 &&
    id.length <= 128 &&
    !id.includes("/") &&
    !id.includes("\\") &&
    !id.includes("..") &&
    SAFE_ID_PATTERN.test(id)
  );
}

/**
 * All generated-data asset URLs are built here, and only here — no other
 * module in the application constructs a fetch path into `generated/`. Uses
 * `import.meta.env.BASE_URL` (always ends with "/") rather than a hardcoded
 * "/" so a future sub-path deployment (ADR-001 D9 follow-on) needs no
 * provider change, only a build-time `base` setting.
 */
function assetUrl(relativePath: string): string {
  return `${import.meta.env.BASE_URL}${relativePath}`;
}

async function fetchJson<T>(relativePath: string, describe: string): Promise<T> {
  let response: Response;
  try {
    response = await fetch(assetUrl(relativePath));
  } catch (cause) {
    throw new DataLoadError(
      `Network error while loading ${describe}: ${cause instanceof Error ? cause.message : String(cause)}`,
      "network"
    );
  }

  if (response.status === 404) {
    throw new DataLoadError(
      `${describe} was not found. Generate the Explorer read model first: ${BUILD_DATA_COMMAND}.`,
      "missing"
    );
  }
  if (!response.ok) {
    throw new DataLoadError(`Failed to load ${describe}: HTTP ${response.status} ${response.statusText}.`, "network");
  }

  try {
    return (await response.json()) as T;
  } catch (cause) {
    throw new DataLoadError(
      `${describe} is not valid JSON (${cause instanceof Error ? cause.message : String(cause)}). ` +
        `Regenerate the read model: ${BUILD_DATA_COMMAND}.`,
      "malformed"
    );
  }
}

const REQUIRED_MANIFEST_STRING_FIELDS = ["readModelVersion", "generatedAt", "generator", "corpusFingerprint"] as const;

function assertManifestShape(data: unknown): asserts data is ReadModelManifest {
  if (typeof data !== "object" || data === null) {
    throw new DataLoadError("manifest.json is malformed: expected a JSON object.", "malformed");
  }
  const m = data as Record<string, unknown>;

  for (const field of REQUIRED_MANIFEST_STRING_FIELDS) {
    if (typeof m[field] !== "string" || (m[field] as string) === "") {
      throw new DataLoadError(`manifest.json is malformed: missing or invalid required field "${field}".`, "malformed");
    }
  }
  if (m.sourceCommit !== null && typeof m.sourceCommit !== "string") {
    throw new DataLoadError('manifest.json is malformed: "sourceCommit" must be a string or null.', "malformed");
  }
  if (typeof m.totalRecords !== "number" || !Number.isFinite(m.totalRecords)) {
    throw new DataLoadError('manifest.json is malformed: missing or invalid required field "totalRecords".', "malformed");
  }
  if (typeof m.counts !== "object" || m.counts === null || Array.isArray(m.counts)) {
    throw new DataLoadError('manifest.json is malformed: missing or invalid required field "counts".', "malformed");
  }
  if (!Array.isArray(m.schemaPrefixes)) {
    throw new DataLoadError('manifest.json is malformed: missing or invalid required field "schemaPrefixes".', "malformed");
  }
}

/**
 * Consumes the RE-01 generated read model over HTTP as static JSON assets
 * (served from apps/research-explorer/generated/ via Vite's publicDir — see
 * vite.config.ts). Validates manifest shape and readModelVersion
 * compatibility before returning anything to the caller; never returns
 * partially-interpreted data.
 *
 * Deliberately does not load edges.json or any record-detail file eagerly —
 * getRecord() is provided for RE-02B and safe to call now, but nothing in
 * RE-02A's application startup calls it.
 */
export class StaticDataProvider implements DataProvider {
  private manifestPromise: Promise<ReadModelManifest> | null = null;
  private indexPromise: Promise<RecordSummary[]> | null = null;

  async getManifest(): Promise<ReadModelManifest> {
    if (!this.manifestPromise) {
      this.manifestPromise = this.loadManifest().catch((error: unknown) => {
        // Do not cache a rejected load: a transient network failure should
        // not permanently poison retries.
        this.manifestPromise = null;
        throw error;
      });
    }
    return this.manifestPromise;
  }

  private async loadManifest(): Promise<ReadModelManifest> {
    const data = await fetchJson<unknown>("manifest.json", "the Explorer manifest");
    assertManifestShape(data);

    if (!isReadModelVersionCompatible(data.readModelVersion)) {
      throw new DataLoadError(
        `Generated read model version "${data.readModelVersion}" is not compatible with this application ` +
          `(this build supports major version ${SUPPORTED_READ_MODEL_MAJOR}). Regenerate the read model with a ` +
          `matching adapter version: ${BUILD_DATA_COMMAND}.`,
        "incompatible"
      );
    }

    return data;
  }

  async listRecords(): Promise<RecordSummary[]> {
    if (!this.indexPromise) {
      this.indexPromise = fetchJson<unknown>("index.json", "the Explorer record index")
        .then((data) => {
          if (!Array.isArray(data)) {
            throw new DataLoadError("index.json is malformed: expected an array.", "malformed");
          }
          return data as RecordSummary[];
        })
        .catch((error: unknown) => {
          this.indexPromise = null;
          throw error;
        });
    }
    return this.indexPromise;
  }

  async getRecord(id: string): Promise<RecordDetail> {
    if (!isSyntacticallySafeId(id)) {
      throw new DataLoadError(`"${id}" is not a valid record ID.`, "invalid_id");
    }

    // Never fetch a record-detail path for an ID that isn't part of the
    // generated index, even if it is syntactically well-formed — this is the
    // "part of the known record set" check, not just a shape check.
    const index = await this.listRecords();
    const known = index.some((r) => r.id === id);
    if (!known) {
      throw new DataLoadError(`Record "${id}" was not found in the generated index.`, "not_found");
    }

    return fetchJson<RecordDetail>(`record-detail/${encodeURIComponent(id)}.json`, `record detail for "${id}"`);
  }
}
